-- README:
--these SQL queries are for setting up your database ready to use the site. This will be your local database so its a sandbox environment
--If you haven't already then download a database client and get it set up locally on your machine. I use postgreSQL and pgAdmin 4
--Once you've set it up then run these sql statements to quickly set up the tables locally on your machine

--in this SQL, we are putting our tables inside our schema called 'public' and are setting ownership to our db user called 'postgres'
--these were the default values for my postgreSQL database when I was setting it up but please ensure it's the same for you
--if you have a different user or schema then please make sure you change it to yours!

--create tables and set owner
CREATE TABLE public.cars (
    "carID" integer NOT NULL,
    model character varying,
    manufacturer character varying,
    "garageID" smallint NOT NULL
);

ALTER TABLE public.cars OWNER TO postgres;


CREATE TABLE public.garages (
    "garageID" smallint NOT NULL,
    name text
);

ALTER TABLE public.garages OWNER TO postgres;

--auto-increment id columns
ALTER TABLE public.cars ALTER COLUMN "carID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."cars_carID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.garages ALTER COLUMN "garageID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."garages_garageID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--setup primary keys
ALTER TABLE ONLY public.cars
    ADD CONSTRAINT "carsTablePK" PRIMARY KEY ("carID");


ALTER TABLE ONLY public.garages
    ADD CONSTRAINT "garageTablePK" PRIMARY KEY ("garageID");

--set up foreign key on garageID
CREATE INDEX "fki_carGarageFK" ON public.cars USING btree ("garageID");

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT "carGarageFK" FOREIGN KEY ("garageID") REFERENCES public.garages("garageID");
